"""users-bookings-rooms-with-nullable2

Revision ID: 17616dfa90a0
Revises: adb2b10f5f30
Create Date: 2023-09-13 12:53:59.606104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17616dfa90a0'
down_revision: Union[str, None] = 'adb2b10f5f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
